### ISSUE TITLE
Arrows and scrolling do not work

### ISSUE THREAD

**Issue by skogsbaer** [skogsbaer/write-your-python-program#142]
What still bothers me is the scroll behaviour. The arrows are not part of the scroll container. They adapt to the new position with a significant delay. They also protrude into the lower area. I have attached a video. 

https://github.com/user-attachments/assets/dc5a7d0b-8b6e-428f-842c-74d3d88848c4

**Comment by hannesbraun** [comment]
The delay should be reduced with 5b27ab396e2084af8ceebc214fcdbebd2b662498. The protruding happens because they are always placed in the body element. Moving them elsewhere is not officially supported by the library. But I'll see what I can do.
