### ISSUE TITLE
Unify Typechecking of `list` and `set`/`dict`

### ISSUE THREAD

**Issue by CodeSteak** [skogsbaer/write-your-python-program#46]
Currently type checking  of lists do not use the protocol-like approach like `set`/`dict`, but `list`s provide slightly better error messaging. Instead `list`'s typechecking is implemented manually.
To not have regression on error messages when unifying, #5 should be resolved first.

**Comment by skogsbaer** [comment]
The wrapper approach taken by list is error-prone, we had several bugs because of that in the past. So if everything that's currently done with the wrapper can be done with protocols, then we should implement lists with protocols.
