### ISSUE TITLE
Nice-to-have: temporarily switch off type-checking

### ISSUE THREAD

**Issue by skogsbaer** [skogsbaer/write-your-python-program#73]
It would be cool if type-checking could be deactive with a function such as `wyppDisableTypeChecking()` and re-enabled by `wyppEnableTypeChecking`.

It's not really important, but if it's easy we should do it.

**Comment by CodeSteak** [comment]
A have some headache with this one.

I see unexpected issues with wrapping. E.g. Protocols are usually wrapped. So what should happen if a Class is passed, that does implement this protocol while type checking is disabled. Then the function stores this now unwrapped object and uses it 
later after checking is enable. 
I think there could be also strange edge cases with container classes like lists.

However disabling without re-enabling could be done with few to none edge cases.
It could be implemented by adding a check to each  `check_and_wrap`.

**Comment by skogsbaer** [comment]
Ok, then I'll close it without fixing. It's not too important.
